config/routes.rb
Rails.application.routes.draw do
  root      'servers#index'
  get       'login'               => 'sessions#login'
  post      'auth/steam/callback' => 'sessions#create'
  match     'auth/failure', :to   => 'sessions#failure', via: [:get, :post]
  delete    'logout'              => 'sessions#destroy'
  get       'privacy_policy'      => 'static_pages#privacy_policy'

  get       'admin/servers'       => 'admin#servers'
  get       'groups/auto'         => 'groups#auto'
  get       'protocols/query'     => 'protocols#query'
  get       'networks/update_all' => 'networks#update_all'
  get       'messages/clear'      => 'messages#clear'
  get       'settings'            => 'users#edit'
  get       'seats'               => 'seats#index'
  get       'seats/update'        => 'seats#update'

  resources :contacts, :only      => [:new, :create]
  resources :games, :param        => :gameid
  resources :servers, :param      => :gameserverip
  resources :users, :param        => :steamid
  resources :groups, :param       => :groupid64
  resources :networks
  resources :messages
  resources :protocols

end

app/models/message.rb
class Message < ActiveRecord::Base
  def Message.display
    m = select("message, message_type").where(show: true).last
  end

  def Message.clear_all
    message = Message.where(:show => true)
    message.each do |m|
	    m.update_attributes(
	      :show	=> false
	    )
    end
    return "Messages cleared." 
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
  	@messages = Message.order("updated_at desc")
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:success] = "Message added."
      redirect_to messages_url
    else
      render 'new'
    end
  end

  def show
    @message = Message.find_by_id(params[:id])
  end

  def edit
  	@message = Message.find_by_id(params[:id])
  end

  def update
  	@message = Message.find_by_id(params[:id])
    if @message.update_attributes(message_params)
      flash[:success] = "Message updated."
      redirect_to messages_url
    else
      render 'edit'
    end
  end

  def destroy
    Message.find_by_id(params[:id]).destroy
    flash[:success] = "Message deleted"
    redirect_to messages_url
  end

  def clear
    if params[:clear].present?
      @clear = Message.clear_all
      flash[:success] = @clear
      redirect_to messages_clear_url
    end
  end

  private
    def message_params
      params.require(:message).permit(:message, :message_type, :show)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        redirect_to root_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end    
end

app/views/messages/_message.html.erb
  <tr class="row">
      <td class="text-left"><%= message.message_type %></td>
      <td class="text-left"><%= message.show %></td>
      <td class="text-left longtext"><%= link_to message.message, edit_message_path(message) %></td>
  </tr>

app/views/messages/clear.html.erb
<% provide(:title, "Clear Messages")  %>
<div class="jumbotron">
<h3 class="center">Clear Messages</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_tag(messages_clear_path, method: "get") do %>
	  <%= hidden_field :clear, "true" %>
	  <%= submit_tag("Clear", class: "btn btn-50 btn-primary pull-left") %>
	  <%= link_to "Back", protocols_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div> 
</div>

app/views/messages/edit.html.erb
<% provide(:title, "Edit Message")  %>
<div class="jumbotron">
<h3 class="center">Edit Message</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

	<%= form_for(@message) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :message %>
	  <%= f.text_field :message, class: 'form-control' %>

	  <%= f.label :message_type %>
	  <%= f.select :message_type, [['success (green)','success'], ['info (blue)','info'], ['warning (yellow)','warning'], ['danger (red)','danger']], {},{:class => 'form-control'} %>

	  <%= f.label :show %>
	  <%= f.select :show, [['yes',true],['no',false]], {}, {:class => 'form-control'} %>

	  <%= f.submit "Save changes", class: "btn btn-33 btn-primary pull-left" %>
	  <%= link_to "Delete", @message, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-33 btn-primary" %>
	  <%= link_to "Back", messages_url, class: "btn btn-33 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>

app/views/messages/index.html.erb
<% provide(:title, "Message List")  %>
<div class="jumbotron">
  <h3 class="center">Messages</h3>

  <table class="table table-striped table-condensed games">
    <thead>
      <tr class="row">
        <th class="col-md-1 text-left">Type</th>
        <th class="col-md-1 text-left">Show</th>
        <th class="col-md-10 text-left">Message</th>
      </tr>
    </thead>
    <tbody>
      <% if @messages.empty? %>
        <tr class="row"><td colspan="3" class="col-md-offset-2 text-center">No Messages Found.</td></tr>
      <% else %>
        <%= render @messages %>
      <% end %>              
    </tbody>
  </table>
</div>

app/views/messages/new.html.erb
<% provide(:title, "Add Message")  %>
<div class="jumbotron">
<h3 class="center">Add Message</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

	<%= form_for(@message) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :message %>
	  <%= f.text_field :message, class: 'form-control' %>

	  <%= f.label :message_type %>
	  <%= f.select :message_type, options_for_select([['success (green)','success'], ['info (blue)','info'], ['warning (yellow)','warning'], ['danger (red)','danger']]), {},{:class => 'form-control'} %>

	  <%= f.label :show %>
	  <%= f.select :show, [['yes',true],['no',false]], {},{:class => 'form-control'} %>

	  <%= f.submit "Save changes", class: "btn btn-50 btn-primary pull-left" %>
	  <%= link_to "Back", messages_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>