config/routes.rb
Rails.application.routes.draw do
  root      'servers#index'
  get       'login'               => 'sessions#login'
  post      'auth/steam/callback' => 'sessions#create'
  match     'auth/failure', :to   => 'sessions#failure', via: [:get, :post]
  delete    'logout'              => 'sessions#destroy'
  get       'privacy_policy'      => 'static_pages#privacy_policy'

  get       'admin/servers'       => 'admin#servers'
  get       'groups/auto'         => 'groups#auto'
  get       'protocols/query'     => 'protocols#query'
  get       'networks/update_all' => 'networks#update_all'
  get       'messages/clear'      => 'messages#clear'
  get       'settings'            => 'users#edit'
  get       'seats'               => 'seats#index'
  get       'seats/update'        => 'seats#update'

  resources :contacts, :only      => [:new, :create]
  resources :games, :param        => :gameid
  resources :servers, :param      => :gameserverip
  resources :users, :param        => :steamid
  resources :groups, :param       => :groupid64
  resources :networks
  resources :messages
  resources :protocols

end

app/models/seat.rb
class Seat < ActiveRecord::Base
  self.primary_key = :seat
  has_many :users, :foreign_key => :seat

  require 'open-uri'
  require 'json'
  require 'matrix'  

  def Seat.update(info)
  	seat = Seat.where(seat: info["seat"]).first_or_create

  	seat.update_attributes(
  	  :clan   => info["clan"],
  	  :handle => info["handle"],
      :updated => true
  	)
  end

  def seat_clan_handle
  	"#{seat} -- #{clan} #{handle}"
  end

  def Seat.update_seats
    string = "https://registration.quakecon.org/?action=byoc_data&response_type=json"

    begin
      parsed = JSON.parse(open(string).read)
    rescue => e
      return "JSON failed to parse #{string}"
    end

    seats = parsed["data"]["seats"]
    tags = parsed["data"]["tags"]

    b62 = Radix::Base.new(('A'..'Z').to_a + ('a'..'z').to_a + ('0'..'9').to_a)
    b10 = Radix::Base.new(Radix::BASE::B10)

    i = 0
    j = 0
    colA = Matrix.build(74,10) {|row, col| i += 1 }
    colB = Matrix.build(74,22) {|row, col| i += 1 }
    colC = Matrix.build(64,12) {|row, col| i += 1 }
    colU = Matrix.build(12,10) {|row, col| i += 1 }

    Seat.update_all(:updated => false)

    seats.each do |seat|

      seatLoc = ''

      seatNum = b10.convert(seat[0], b62).to_i + 1

      if colA.index(seatNum) != nil
        seatLoc << 'A' + sprintf('%02d',((colA.index(seatNum)[0]) + 1)) + '-' + sprintf('%02d',((colA.index(seatNum)[1]) + 1))
      elsif colB.index(seatNum) != nil
        seatLoc << 'B' + sprintf('%02d',((colB.index(seatNum)[0]) + 1)) + '-' + sprintf('%02d',((colB.index(seatNum)[1]) + 1))
      elsif colC.index(seatNum) != nil
        seatLoc << 'C' + sprintf('%02d',((colC.index(seatNum)[0]) + 1)) + '-' + sprintf('%02d',((colC.index(seatNum)[1]) + 1))
      elsif colU.index(seatNum) != nil
        num = seatNum - 3137
        table = (num/10).floor + 1
        row = (num%10).floor + 1

        digit = 13 - table + (10 - row)

        if row == 1
          digit += 2 * (table - 1)
        end

        seatLoc << 'UAC-' + sprintf('%02d', digit)
      end

      if seat[1][0] == ":"
        clan = ''
      else
        clanSplit = seat[1].split(":",2)
        clan = tags[clanSplit[0]]
      end

      if seat[1][-1,1] == ":"
        handle = 'Reserved'
      else
        handleSplit = seat[1].split(":",2)
        handle = handleSplit[1]
      end

      info = { "seat"   => seatLoc,
           "clan"   => clan,
           "handle" => handle
           }

      Seat.update(info)
      j+=1
    end
    Seat.where(:updated => false).update_all(:handle => nil, :clan => nil)
    return "processed #{j} seats."  
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
	@seats = Seat.order("seat asc")
	@seats = Seat.order(params[:sort])  if params[:sort].present?
  end

  def update
    if params[:update].present?
      @update = Seat.update_seats
      flash[:success] = @update
      redirect_to seats_update_url
    end
  end

  private
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        redirect_to root_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end 
end

app/views/seats/_seat.html.erb
  <tr class="row">
      <td class="text-left"><%= seat.seat %></td>
      <td class="text-left longtext"><%= seat.clan %></td>      
      <td class="text-left longtext"><%= seat.handle %></td>
  </tr>

app/views/seats/index.html.erb
<% provide(:title, "Seat List")  %>
<div class="jumbotron">
  <h3 class="center">Seats</h3>

  <table class="table table-striped table-condensed games">
    <thead>
      <tr class="row">
        <th class="col-md-1 text-left"><%= link_to "seat", :sort => "seat" %></th>
        <th class="col-md-4 text-left"><%= link_to "clan", :sort => "clan" %></th>        
        <th class="col-md-7 text-left"><%= link_to "handle", :sort => "handle" %></th>

      </tr>
    </thead>
    <tbody>
      <% if @seats.empty? %>
        <tr class="row"><td colspan="3" class="col-md-offset-2 text-center">No Seats Found.</td></tr>
      <% else %>
        <%= render @seats %>
      <% end %>             
    </tbody>
  </table>
</div>

app/views/seats/update.html.erb
<% provide(:title, "Update Seats")  %>
<div class="jumbotron">
<h3 class="center">Update Seats</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_tag(seats_update_path, method: "get") do %>
	  <%= hidden_field :update, "true" %>
	  <%= submit_tag("Update", class: "btn btn-50 btn-primary pull-left") %>
	  <%= link_to "Back", protocols_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div> 
</div>