config/routes.rb
Rails.application.routes.draw do
  root      'servers#index'
  get       'login'               => 'sessions#login'
  post      'auth/steam/callback' => 'sessions#create'
  match     'auth/failure', :to   => 'sessions#failure', via: [:get, :post]
  delete    'logout'              => 'sessions#destroy'
  get       'privacy_policy'      => 'static_pages#privacy_policy'

  get       'admin/servers'       => 'admin#servers'
  get       'groups/auto'         => 'groups#auto'
  get       'protocols/query'     => 'protocols#query'
  get       'networks/update_all' => 'networks#update_all'
  get       'messages/clear'      => 'messages#clear'
  get       'settings'            => 'users#edit'
  get       'seats'               => 'seats#index'
  get       'seats/update'        => 'seats#update'

  resources :contacts, :only      => [:new, :create]
  resources :games, :param        => :gameid
  resources :servers, :param      => :gameserverip
  resources :users, :param        => :steamid
  resources :groups, :param       => :groupid64
  resources :networks
  resources :messages
  resources :protocols

end

app/models/network.rb
class Network < ActiveRecord::Base
  require "ipaddr"

  def Network.location(i)
    ip = IPAddr.new(i).to_i

    network = 'wan'

    Network.all.each do |r|
      min = IPAddr.new(r.min).to_i      
      max = IPAddr.new(r.max).to_i

      if (min..max)===ip
        network = r.network

        if network == "banned"
          return network
        end
      end
    end

    return network
  end

  def Network.update_all
    i = 0
    Server.all.each do |server|
      network = Network.location(server.ip)
      Server.update_network(server.gameserverip, network)
      i+=1
    end
    return "Updated networks for #{i} servers." 
  end  
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
  	@networks = Network.order("network asc")
  end

  def new
    @network = Network.new
  end

  def create
    @network = Network.new(network_params)
    if @network.save
      flash[:success] = "Network added."
      redirect_to networks_url
    else
      render 'new'
    end
  end

  def edit
  	@network = Network.find_by_id(params[:id])
  end

  def update
  	@network = Network.find_by_id(params[:id])
    if @network.update_attributes(network_params)
      flash[:success] = "Network updated."
      redirect_to networks_url
    else
      render 'edit'
    end
  end

  def update_all
    if params[:update].present?
      @update = Network.update_all
      flash[:success] = @update
      redirect_to networks_url
    end    
  end

  def destroy
    Network.find_by_id(params[:id]).destroy
    flash[:success] = "Network deleted"
    redirect_to networks_url
  end

  private
    def network_params
      params.require(:network).permit(:network, :min, :max)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        redirect_to root_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end    
end

app/views/networks/_network.html.erb
  <tr class="row">
      <td class="text-left longtext"><%= link_to network.network, edit_network_path(network) %></td>
      <td class="text-left"><%= link_to network.min, edit_network_path(network) %></td>
      <td class="text-left"><%= link_to network.max, edit_network_path(network) %></td>
  </tr>

app/views/networks/edit.html.erb
<% provide(:title, "Edit Network")  %>
<div class="jumbotron">
<h3 class="center">Edit Network</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

	<%= form_for(@network) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :network %>
	  <%= f.text_field :network, class: 'form-control' %>

	  <%= f.label :min %>
	  <%= f.text_field :min, class: 'form-control' %>

	  <%= f.label :max %>
	  <%= f.text_field :max, class: 'form-control' %>

	  <%= f.submit "Save changes", class: "btn btn-33 btn-primary pull-left" %>
	  <%= link_to "Delete", @network, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-33 btn-primary" %>
	  <%= link_to "Back", networks_url, class: "btn btn-33 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>

app/views/networks/index.html.erb
<% provide(:title, "Network List")  %>
<div class="jumbotron">
  <h3 class="center">Networks</h3>

  <table class="table table-striped table-condensed games">
    <thead>
      <tr class="row">
        <th class="col-md-8 text-left">Network</th>
        <th class="col-md-2 text-left">Min</th>
        <th class="col-md-2 text-left">Max</th>
      </tr>
    </thead>
    <tbody>
      <% if @networks.empty? %>
        <tr class="row"><td colspan="3" class="col-md-offset-2 text-center">No Networks Found.</td></tr>
      <% else %>
        <%= render @networks %>
      <% end %>             
    </tbody>
  </table>
</div>

app/views/networks/new.html.erb
<% provide(:title, "Add Network")  %>
<div class="jumbotron">
<h3 class="center">Add Network</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

	<%= form_for(@network) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :network %>
	  <%= f.text_field :network, class: 'form-control' %>

	  <%= f.label :min %>
	  <%= f.text_field :min, class: 'form-control' %>

	  <%= f.label :max %>
	  <%= f.text_field :max, class: 'form-control' %>

	  <%= f.submit "Save changes", class: "btn btn-50 btn-primary pull-left" %>
	  <%= link_to "Back", networks_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>

app/views/networks/update_all.html.erb
<% provide(:title, "Update Networks")  %>
<div class="jumbotron">
<h3 class="center">Update Networks</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_tag(networks_update_all_path, method: "get") do %>
	  <%= hidden_field :update, "true" %>
	  <%= submit_tag("Update", class: "btn btn-50 btn-primary pull-left") %>
	  <%= link_to "Back", networks_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div> 
</div>