config/routes.rb
Rails.application.routes.draw do
  root      'servers#index'
  get       'login'               => 'sessions#login'
  post      'auth/steam/callback' => 'sessions#create'
  match     'auth/failure', :to   => 'sessions#failure', via: [:get, :post]
  delete    'logout'              => 'sessions#destroy'
  get       'privacy_policy'      => 'static_pages#privacy_policy'

  get       'admin/servers'       => 'admin#servers'
  get       'groups/auto'         => 'groups#auto'
  get       'protocols/query'     => 'protocols#query'
  get       'networks/update_all' => 'networks#update_all'
  get       'messages/clear'      => 'messages#clear'
  get       'settings'            => 'users#edit'
  get       'seats'               => 'seats#index'
  get       'seats/update'        => 'seats#update'

  resources :contacts, :only      => [:new, :create]
  resources :games, :param        => :gameid
  resources :servers, :param      => :gameserverip
  resources :users, :param        => :steamid
  resources :groups, :param       => :groupid64
  resources :networks
  resources :messages
  resources :protocols

end

app/models/group.rb
class Group < ActiveRecord::Base
  self.primary_key = :groupid64
  require 'open-uri'	

  def Group.auto_add(url)
    html = open(url) 
    page = Nokogiri::HTML(html.read)

    name = page.css('title').text.strip
    name.slice!("Steam Community :: Group :: ")

	if id = page.xpath("//div[contains(@class,'joinchat_bg')]")
	  groupid64 = id[0]['onclick']
	  groupid64.slice!("window.location='steam://friends/joinchat/")
	  groupid64.slice!("'")
	end

	group = Group.where(groupid64: groupid64).first_or_create
	group.update_attributes(
	  :name		=> name,
	  :url		=> url
	)
  end 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
  	@groups = Group.order("name asc")
  end

  def new
    @group = Group.new
  end

  def auto
    if params[:auto].present?
      @group = Group.auto_add(params[:url])
      flash[:success] = "Group updated."
      redirect_to groups_url
    end
  end

  def create
      @group = Group.new(group_params)
      if @group.save
        flash[:success] = "Group added."
        redirect_to groups_url
      else
        render 'new'
      end
  end

  def edit
  	@group = Group.find_by_groupid64(params[:groupid64])
  end

  def update
  	@group = Group.find_by_groupid64(params[:groupid64])
    if @group.update_attributes(group_params)
      flash[:success] = "Group updated."
      redirect_to groups_url
    else
      render 'edit'
    end
  end

  def destroy
    Group.find_by_groupid64(params[:groupid64]).destroy
    flash[:success] = "Group deleted"
    redirect_to groups_url
  end


  private
    def group_params
      params.require(:group).permit(:groupid64, :name, :url, :enabled)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        redirect_to root_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end    
end

app/views/groups/_group.html.erb
  <tr class="row">
      <td class="text-left"><%= group.groupid64 %></td>
      <td class="text-left longtext"><%= link_to group.name, edit_group_path(group) %></td>      
      <td class="text-left"><%= group.enabled %></td>
  </tr>

app/views/groups/auto.html.erb
<% provide(:title, "New Group")  %>
<div class="jumbotron">
<h3 class="center">Add Group</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_tag(groups_auto_path, method: "get") do %>
	  <%= hidden_field :auto, "true" %>
	  <%= text_field_tag(:url, nil, :placeholder => "http://steamcommunity.com/groups/ProPartyPeople", :class => 'form-control') %>
	  <%= submit_tag("Add", class: "btn btn-50 btn-primary pull-left") %>
	  <%= link_to "Back", groups_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>

app/views/groups/edit.html.erb
<% provide(:title, "Edit Group")  %>
<div class="jumbotron">
<h3 class="center">Edit Group</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

	<%= form_for(@group) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :id %>
	  <%= f.text_field :groupid64, class: 'form-control', :disabled => true %>

	  <%= f.label :name %>
	  <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :url %>
	  <%= f.text_field :url, class: 'form-control' %>

	  <%= f.label :enabled %>
	  <%= f.select :enabled, [['yes',true],['no',false]], {},{:class => 'form-control'} %>

	  <%= f.submit "Save", class: "btn btn-33 btn-primary pull-left" %>
	  <%= link_to "Delete", @group, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-33 btn-primary" %>
	  <%= link_to "Back", groups_url, class: "btn btn-33 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>

app/views/groups/index.html.erb
<% provide(:title, "Groups List")  %>
<div class="jumbotron">
  <h3 class="center">Groups</h3>
  <table class="table table-striped table-condensed games">
    <thead>
      <tr class="row">
        <th class="col-md-2 text-left">ID</th>
        <th class="col-md-9 text-left">Name</th>
        <th class="col-md-1 text-left">Enabled</th>        
      </tr>
    </thead>
    <tbody>
      <% if @groups.empty? %>
        <tr class="row"><td colspan="3" class="col-md-offset-2 text-center">No Groups Found.</td></tr>
      <% else %>
        <%= render @groups %>
      <% end %>            
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<% provide(:title, "New Group")  %>
<div class="jumbotron">
<h3 class="center">Add Group</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for(@group) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :id %>
	  <%= f.text_field :groupid64, class: 'form-control' %>

	  <%= f.label :name %>
	  <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :url %>
	  <%= f.text_field :url, class: 'form-control' %>

	  <%= f.submit "Save changes", class: "btn btn-50 btn-primary pull-left" %>
	  <%= link_to "Back", groups_url, class: "btn btn-50 btn-primary pull-right" %>
	<% end %>
  </div>
</div>
</div>